#!/bin/bash

# Get IPv4 addresses using ifconfig and filter out active ones
active_ips=$(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*')

# Display active IPv4 addresses
echo "Active IPv4 Addresses:"
echo "$active_ips"
